### ISSUE TITLE
on Colab: ignore_these_misspells.txt missing

### ISSUE THREAD

**Issue by L-ENA** [ja-mcm/OCRfixr#2]
Hi,

installing this library and running the example on my local machine works perfectly, thanks for this great library! 

Since I don't have a GPU I tried it on Google's Colab also, but for some reason this is failing. Since some people don't have GPUs and lots of online blogs share code via Colab I thought that its maybe worth flagging this to you.

I've just tried to install this library via PIP on Colab, using the following lines of code:

!pip install OCRfixr
from ocrfixr import spellcheck

However, on the import statement the stack trace tells me that this file is missing
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/dist-packages/ocrfixr/data/ignore_these_misspells.txt'

Here the full stack:
/usr/local/lib/python3.7/dist-packages/ocrfixr/__init__.py in <module>()
      5 __version__ = '0.1.0'
      6 
----> 7 from .spellcheck import spellcheck
      8 from .unsplit import unsplit

/usr/local/lib/python3.7/dist-packages/ocrfixr/spellcheck.py in <module>()
     20 
     21 # List of words NOT in SCOWL 70 that we should ignore anyways
---> 22 ignore_misreads = (ocrfixr / "data" / "ignore_these_misspells.txt").read_text(encoding='utf-8').split()
     23 ignore_set_from_pkg = set(ignore_misreads)
     24 

/usr/lib/python3.7/pathlib.py in read_text(self, encoding, errors)
   1219         Open the file in text mode, read it, and close the file.
   1220         """
-> 1221         with self.open(mode='r', encoding=encoding, errors=errors) as f:
   1222             return f.read()
   1223 

/usr/lib/python3.7/pathlib.py in open(self, mode, buffering, encoding, errors, newline)
   1206             self._raise_closed()
   1207         return io.open(self, mode, buffering, encoding, errors, newline,
-> 1208                        opener=self._opener)
   1209 
   1210     def read_bytes(self):

/usr/lib/python3.7/pathlib.py in _opener(self, name, flags, mode)
   1061     def _opener(self, name, flags, mode=0o666):
   1062         # A stub for the opener argument to built-in open()
-> 1063         return self._accessor.open(self, flags, mode)
   1064 
   1065     def _raw_open(self, flags, mode=0o777):

FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/dist-packages/ocrfixr/data/ignore_these_misspells.txt'

I saw that this file was actually available on git. So I tried to install from git directly, which resulted in this similar error, also on the line where spellcheck is imported, but regarding the file 'SCOWL_70.txt'

**Comment by ja-mcm** [comment]
Thanks for this heads up. It looks like Colab's filesystem is case-sensitive, so it didn't recognize the uppercased filenames.  OCRfixr v1.4.2.3 addresses this & after reinstalling, Colab runs it just fine.
