### ISSUE TITLE
Pip resolution errror. All versions of TensorFlow depenend on Numpy 1.20

### ISSUE THREAD

**Issue by wrmthorne** [ja-mcm/OCRfixr#5]
ERROR: Cannot install OCRfixr and ocrfixr==1.5 because these package versions have conflicting dependencies.

The conflict is caused by:
    ocrfixr 1.5 depends on numpy~=1.19.2
    tensorflow 2.11.0 depends on numpy>=1.20
    ocrfixr 1.5 depends on numpy~=1.19.2
    tensorflow 2.10.1 depends on numpy>=1.20
    ocrfixr 1.5 depends on numpy~=1.19.2
    tensorflow 2.10.0 depends on numpy>=1.20
    ocrfixr 1.5 depends on numpy~=1.19.2
    tensorflow 2.9.3 depends on numpy>=1.20
    ocrfixr 1.5 depends on numpy~=1.19.2
    tensorflow 2.9.2 depends on numpy>=1.20
    ocrfixr 1.5 depends on numpy~=1.19.2
    tensorflow 2.9.1 depends on numpy>=1.20
    ocrfixr 1.5 depends on numpy~=1.19.2
    tensorflow 2.9.0 depends on numpy>=1.20
    ocrfixr 1.5 depends on numpy~=1.19.2
    tensorflow 2.8.4 depends on numpy>=1.20
    ocrfixr 1.5 depends on numpy~=1.19.2
    tensorflow 2.8.3 depends on numpy>=1.20
    ocrfixr 1.5 depends on numpy~=1.19.2
    tensorflow 2.8.2 depends on numpy>=1.20
    ocrfixr 1.5 depends on numpy~=1.19.2
    tensorflow 2.8.1 depends on numpy>=1.20
    ocrfixr 1.5 depends on numpy~=1.19.2
    tensorflow 2.8.0 depends on numpy>=1.20

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by wrmthorne** [comment]
I have managed to get the package to work by setting the NumPy version to >= 1.20.0 and the Tensorflow version to 2.9.0

**Comment by ja-mcm** [comment]
I changed the dependency & things compiled on my end. Thanks for sharing this!
